### ISSUE TITLE
Go 1.23 build error on Debian 12 64bit

### ISSUE THREAD

**Issue by zoonderkins** [folbricht/routedns#424]
Here is the error 

```
➜ ~ GO111MODULE=on go install  github.com/folbricht/routedns/cmd/routedns@latest
go: downloading github.com/folbricht/routedns v0.1.88
go: downloading github.com/sthorne/odoh-go v1.0.4
go: finding module for package github.com/BurntSushi/toml/internal
go: finding module for package github.com/emirpasic/gods/queues/linkedlistqueue
go: finding module for package github.com/emirpasic/gods/stacks/linkedliststack
go: finding module for package golang.org/x/exp/rand
go: downloading golang.org/x/exp v0.0.0-20250106191152-7588d65b2ba8
go: found github.com/BurntSushi/toml/internal in github.com/BurntSushi/toml v1.4.0
go: found golang.org/x/exp/rand in golang.org/x/exp v0.0.0-20250106191152-7588d65b2ba8
go: finding module for package github.com/emirpasic/gods/queues/linkedlistqueue
go: finding module for package github.com/emirpasic/gods/stacks/linkedliststack
go/pkg/mod/github.com/heimdalr/dag@v1.4.0/visitor.go:6:2: module github.com/emirpasic/gods@latest found (v1.18.1), but does not contain package github.com/emirpasic/gods/queues/linkedlistqueue
go/pkg/mod/github.com/heimdalr/dag@v1.4.0/visitor.go:7:2: module github.com/emirpasic/gods@latest found (v1.18.1), but does not contain package github.com/emirpasic/gods/stacks/linkedliststack
```

Also when I try to download prebuild binary, no file exist
```
https://github.com/cbuijs/routedns-binaries/raw/master/linux/amd64/routedns
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-01-11 07:39:47 ERROR 404: Not Found.```

**Comment by folbricht** [comment]
Can you try again? You don't really need the `GO111MODULE=on` bit. Also make sure you aren't in directory that's part of another Go module. What version of Go are you using?

This is what I see after clearing the module cache with `go clean -modcache`.
```
$ go install  github.com/folbricht/routedns/cmd/routedns@latest
go: downloading github.com/folbricht/routedns v0.1.89
go: downloading github.com/BurntSushi/toml v1.3.2
go: downloading github.com/heimdalr/dag v1.4.0
go: downloading github.com/RackSec/srslog v0.0.0-20180709174129-a4725f04ec91
go: downloading github.com/redis/go-redis/v9 v9.5.1
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/spf13/cobra v1.8.0
go: downloading github.com/jtacoma/uritemplates v1.0.0
go: downloading github.com/miekg/dns v1.1.59
go: downloading github.com/oschwald/maxminddb-golang v1.12.0
go: downloading github.com/pion/dtls/v2 v2.2.11
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/quic-go/quic-go v0.48.2
go: downloading github.com/txthinking/socks5 v0.0.0-20230325130024-4230056ae301
go: downloading golang.org/x/net v0.28.0
go: downloading github.com/emirpasic/gods v1.18.1
go: downloading github.com/google/uuid v1.6.0
go: downloading github.com/cespare/xxhash/v2 v2.3.0
go: downloading github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f
go: downloading golang.org/x/sys v0.28.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/pion/logging v0.2.2
go: downloading github.com/pion/transport/v2 v2.2.5
go: downloading github.com/quic-go/qpack v0.5.1
go: downloading golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842
go: downloading github.com/txthinking/runnergroup v0.0.0-20230325130830-408dc5853f86
go: downloading github.com/patrickmn/go-cache v2.1.0+incompatible
go: downloading golang.org/x/crypto v0.31.0
go: downloading golang.org/x/text v0.21.0
```

**Comment by zoonderkins** [comment]
Here is what I try so far.

```
250113-06:33 root@tw1:~
➜ ~ go install  github.com/folbricht/routedns/cmd/routedns@latest
go: downloading github.com/folbricht/routedns v0.1.89
go: finding module for package github.com/BurntSushi/toml/internal
go: finding module for package github.com/emirpasic/gods/queues/linkedlistqueue
go: finding module for package github.com/emirpasic/gods/stacks/linkedliststack
go: finding module for package golang.org/x/exp/rand
go: found github.com/BurntSushi/toml/internal in github.com/BurntSushi/toml v1.4.0
go: found golang.org/x/exp/rand in golang.org/x/exp v0.0.0-20250106191152-7588d65b2ba8
go: finding module for package github.com/emirpasic/gods/queues/linkedlistqueue
go: finding module for package github.com/emirpasic/gods/stacks/linkedliststack
go/pkg/mod/github.com/heimdalr/dag@v1.4.0/visitor.go:6:2: module github.com/emirpasic/gods@latest found (v1.18.1), but does not contain package github.com/emirpasic/gods/queues/linkedlistqueue
go/pkg/mod/github.com/heimdalr/dag@v1.4.0/visitor.go:7:2: module github.com/emirpasic/gods@latest found (v1.18.1), but does not contain package github.com/emirpasic/gods/stacks/linkedliststack
250113-06:33 root@tw1:~
➜ ~ go clean -modcache
250113-06:34 root@tw1:~
➜ ~ go install  github.com/folbricht/routedns/cmd/routedns@latest
go: downloading github.com/folbricht/routedns v0.1.89
go: downloading github.com/BurntSushi/toml v1.3.2
go: downloading github.com/RackSec/srslog v0.0.0-20180709174129-a4725f04ec91
go: downloading github.com/heimdalr/dag v1.4.0
go: downloading github.com/redis/go-redis/v9 v9.5.1
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/spf13/cobra v1.8.0
go: downloading github.com/jtacoma/uritemplates v1.0.0
go: downloading github.com/miekg/dns v1.1.59
go: downloading github.com/oschwald/maxminddb-golang v1.12.0
go: downloading github.com/pion/dtls/v2 v2.2.11
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/quic-go/quic-go v0.48.2
go: downloading github.com/txthinking/socks5 v0.0.0-20230325130024-4230056ae301
go: downloading golang.org/x/net v0.28.0
go: downloading github.com/emirpasic/gods v1.18.1
go: downloading github.com/google/uuid v1.6.0
go: downloading github.com/cespare/xxhash/v2 v2.3.0
go: downloading github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f
go: downloading golang.org/x/sys v0.28.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/pion/logging v0.2.2
go: downloading github.com/pion/transport/v2 v2.2.5
go: downloading golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842
go: downloading github.com/quic-go/qpack v0.5.1
go: downloading github.com/patrickmn/go-cache v2.1.0+incompatible
go: downloading github.com/txthinking/runnergroup v0.0.0-20230325130830-408dc5853f86
go: downloading golang.org/x/crypto v0.31.0
go: downloading golang.org/x/text v0.21.0
go: finding module for package github.com/BurntSushi/toml/internal
go: downloading github.com/BurntSushi/toml v1.4.0
go: finding module for package github.com/emirpasic/gods/queues/linkedlistqueue
go: finding module for package github.com/emirpasic/gods/stacks/linkedliststack
go: finding module for package golang.org/x/exp/rand
go: downloading golang.org/x/exp v0.0.0-20250106191152-7588d65b2ba8
go: found github.com/BurntSushi/toml/internal in github.com/BurntSushi/toml v1.4.0
go: found golang.org/x/exp/rand in golang.org/x/exp v0.0.0-20250106191152-7588d65b2ba8
go: finding module for package github.com/emirpasic/gods/queues/linkedlistqueue
go: finding module for package github.com/emirpasic/gods/stacks/linkedliststack
go/pkg/mod/github.com/heimdalr/dag@v1.4.0/visitor.go:6:2: module github.com/emirpasic/gods@latest found (v1.18.1), but does not contain package github.com/emirpasic/gods/queues/linkedlistqueue
go/pkg/mod/github.com/heimdalr/dag@v1.4.0/visitor.go:7:2: module github.com/emirpasic/gods@latest found (v1.18.1), but does not contain package github.com/emirpasic/gods/stacks/linkedliststack
250113-06:34 root@tw1:~
➜ ~ go version
go version go1.23.4 linux/amd64
```

**Comment by cbuijs** [comment]
I fixed the builds in re routedns-binaries repo (I maintain it). It was a mismatch of module-versions and the new go version. Meanwhile all maintainers adapted, so it works again (did not had to fix anything). My repo will be updated in the next hour or so.

Also, don't use `GO111MODULE=on`, then you are sure the (recommended/tested) revisions mentioned from the RouteDNS build are actually used. It brings more problems then gain.

**Comment by cbuijs** [comment]
@folbricht Maybe elaborate or change the line in [README.md](https://github.com/folbricht/routedns/blob/master/README.md) about `go11module=on` (in de installation section)? I always use `off` myself.

**Comment by folbricht** [comment]
Updated the instructions in https://github.com/folbricht/routedns/pull/431

@zoonderkins Still not sure why it's failing for you. Almost looks like the module cache is damaged. Did an earlier download fail to write to disk perhaps? Might be worth trying to delete the cache manually, basically delete `$HOME/go/pkg/mod/github.com/heimdalr/`

**Comment by zoonderkins** [comment]
Still no luck ~ 

```
root@tw1:~
➜ ~ rm -rf $HOME/go/pkg/mod/github.com/heimdalr/
250114-09:47 root@tw1:~
➜ ~ go install  github.com/folbricht/routedns/cmd/routedns@latest
go: downloading github.com/folbricht/routedns v0.1.96
go: downloading github.com/cloudflare/odoh-go v1.0.1-0.20230926114050-f39fa019b017
go: downloading github.com/cisco/go-hpke v0.0.0-20230407100446-246075f83609
go: downloading github.com/cisco/go-tls-syntax v0.0.0-20200617162716-46b0cfb76b9b
go: downloading github.com/cloudflare/circl v1.3.7
go: finding module for package github.com/BurntSushi/toml/internal
go: finding module for package github.com/emirpasic/gods/queues/linkedlistqueue
go: finding module for package github.com/emirpasic/gods/stacks/linkedliststack
go: finding module for package golang.org/x/exp/rand
go: found github.com/BurntSushi/toml/internal in github.com/BurntSushi/toml v1.4.0
go: found golang.org/x/exp/rand in golang.org/x/exp v0.0.0-20250106191152-7588d65b2ba8
go: finding module for package github.com/emirpasic/gods/queues/linkedlistqueue
go: finding module for package github.com/emirpasic/gods/stacks/linkedliststack
go/pkg/mod/github.com/heimdalr/dag@v1.4.0/visitor.go:6:2: module github.com/emirpasic/gods@latest found (v1.18.1), but does not contain package github.com/emirpasic/gods/queues/linkedlistqueue
go/pkg/mod/github.com/heimdalr/dag@v1.4.0/visitor.go:7:2: module github.com/emirpasic/gods@latest found (v1.18.1), but does not contain package github.com/emirpasic/gods/stacks/linkedliststack

root@tw1:~
➜ ~ cd go/pkg/mod
250114-09:48 root@tw1:~/go/pkg/mod
➜ mod ls
cache  github.com  golang.org
250114-09:48 root@tw1:~/go/pkg/mod
➜ mod rm -rf github.com/
250114-09:48 root@tw1:~/go/pkg/mod
➜ mod cd
250114-09:48 root@tw1:~

➜ ~ go install  github.com/folbricht/routedns/cmd/routedns@latest
go: finding module for package github.com/BurntSushi/toml/internal
go: finding module for package github.com/emirpasic/gods/queues/linkedlistqueue
go: finding module for package github.com/emirpasic/gods/stacks/linkedliststack
go: finding module for package golang.org/x/exp/rand
go: found github.com/BurntSushi/toml/internal in github.com/BurntSushi/toml v1.4.0
go: found golang.org/x/exp/rand in golang.org/x/exp v0.0.0-20250106191152-7588d65b2ba8
go: finding module for package github.com/emirpasic/gods/queues/linkedlistqueue
go: finding module for package github.com/emirpasic/gods/stacks/linkedliststack
go/pkg/mod/github.com/heimdalr/dag@v1.4.0/visitor.go:6:2: module github.com/emirpasic/gods@latest found (v1.18.1), but does not contain package github.com/emirpasic/gods/queues/linkedlistqueue
go/pkg/mod/github.com/heimdalr/dag@v1.4.0/visitor.go:7:2: module github.com/emirpasic/gods@latest found (v1.18.1), but does not contain package github.com/emirpasic/gods/stacks/linkedliststack
```

**Comment by folbricht** [comment]
Thanks for trying that. Would you mind trying it again, but after clearing all modules from the cache with `rm -rf $HOME/go/pkg/mod/` ? That should put everything into a consistent state.

**Comment by zoonderkins** [comment]
Still not working even removed `rm -rf $HOME/go/pkg/mod/`
